read dataset

In [1]:
import pandas as pd

df = pd.read_csv("../dataset/qgenllm-updated-20260209.csv", sep=";")
print(df.shape)

display(df.head())

print("ONTOLOGIES")
print(df.ontology.value_counts())

(513985, 10)

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short
0,[X] SubclassOf([prop] some [Y]),CarnivorousPlant SubclassOf(eats some Animal),Does [X] [prop/*OP_VERB-infinitive] some [Y]?,Does a carnivorous plant eat some animal?,op_Yes-No-2-part-1-rel+1-quant-some,OP_VERB,AWO,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,verb
1,[X] SubclassOf([prop] some [Y]),Warthog SubclassOf(eats some Grass),Does [X] [prop/*OP_VERB-infinitive] some [Y]?,Does a warthog eat some grass?,op_Yes-No-2-part-1-rel+1-quant-some,OP_VERB,AWO,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,verb
2,[X] SubclassOf([prop] some [Y]),Warthog SubclassOf(eats some Gras),Does [X] [prop/*OP_VERB-infinitive] some [Y]?,Does a warthog eat some gras?,op_Yes-No-2-part-1-rel+1-quant-some,OP_VERB,AWO,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,verb
3,[X] SubclassOf([prop] some [Y]),Warthog SubclassOf(eats some PlantParts),Does [X] [prop/*OP_VERB-infinitive] some [Y]?,Does a warthog eat some plant parts?,op_Yes-No-2-part-1-rel+1-quant-some,OP_VERB,AWO,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,verb
4,[X] SubclassOf([prop] some [Y]),Warthog SubclassOf(eats some Root),Does [X] [prop/*OP_VERB-infinitive] some [Y]?,Does a warthog eat some root?,op_Yes-No-2-part-1-rel+1-quant-some,OP_VERB,AWO,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,verb

ONTOLOGIES
ontology
Stuff           340412
Pizza            62701
BioTop           61835
Cultural-On      22668
swo              19257
exmo              4009
MFOEM             1327
AWO               1153
CopyrightAll       302
bcio               249
olia                72
Name: count, dtype: int64

In [3]:
biotop1 = df[df.ontology == "BioTop"]
print(biotop1.groupby("question_type").count())

biotop2 = df[df.ontology == "BioTop"]
print(biotop2[["question", "question_type"]].iloc[1])

                                  axiom_pattern  axiom  template  question  \
question_type
Definition                                  149    149       149       149
What-1-part-1-rel                          6854   6854      6854      6854
What-2-part-1-rel                          6854   6854      6854      6854
What-2-part-1-rel-quant-only               6160   6160      6160      6160
What-2-part-1-rel-quant-some                694    694       694       694
Yes-No-2-part-1-rel                       20562  20562     20562     20562
Yes-No-2-part-1-rel+1-quant-only          18480  18480     18480     18480
Yes-No-2-part-1-rel+1-quant-some           2082   2082      2082      2082

                                  op_category  ontology   file  \
question_type
Definition                                149       149    149
What-1-part-1-rel                        6854      6854   6854
What-2-part-1-rel                        6854      6854   6854
What-2-part-1-rel-quant-only             6160      6160   6160
What-2-part-1-rel-quant-some              694       694    694
Yes-No-2-part-1-rel                     20562     20562  20562
Yes-No-2-part-1-rel+1-quant-only        18480     18480  18480
Yes-No-2-part-1-rel+1-quant-some         2082      2082   2082

                                  question_type_short  op_category_short
question_type
Definition                                        149                149
What-1-part-1-rel                                6854               6854
What-2-part-1-rel                                6854               6854
What-2-part-1-rel-quant-only                     6160               6160
What-2-part-1-rel-quant-some                      694                694
Yes-No-2-part-1-rel                             20562              20562
Yes-No-2-part-1-rel+1-quant-only                18480              18480
Yes-No-2-part-1-rel+1-quant-some                 2082               2082
question         What is universe?
question_type           Definition
Name: 1403, dtype: object

In [4]:
display(df[df.ontology == "BioTop"].sample(5))
biotop = df[df.ontology == "BioTop"]
# print question_types
print(biotop.question_type.value_counts())

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short
49076,[X] SubclassOf([prop] some [Y]),Universe SubclassOf(isProjectionOf some Immate...,True or false: [X] is [prop/*OP_IS_NOUNS_PREP]...,True or false: Universe is a projection of onl...,Yes-No-2-part-1-rel+1-quant-only,OP_IS_NOUNS_PREP,BioTop,Yes-No-2-part-1-rel+1-quant-only.csv,yn2p1r1_1_qo,is_noun_prep
16331,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] some...","Universe SubclassOf(MaterialObject),Universe S...",Which [X/noArticle] [prop/*OP_HAS_NOUNS-third]...,Which material object has a patient that is on...,What-2-part-1-rel-quant-only,OP_HAS_NOUNS,BioTop,What-2-part-1-rel-quant-only.csv,w2p1r_qo,has_nouns
42236,[X] SubclassOf([prop] some [Y]),OrganismPart SubclassOf(isBearerOf some Object...,True or false: [X] is [prop/*OP_IS_NOUNS_PREP]...,True or false: An organism part is a bearer of...,Yes-No-2-part-1-rel,OP_IS_NOUNS_PREP,BioTop,Yes-No-2-part-1-rel.csv,yn2p1r,is_noun_prep
52332,[X] SubclassOf([prop] some [Y]),Universe SubclassOf(hasAgent some Universe),Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does universe have an agent that is only unive...,Yes-No-2-part-1-rel+1-quant-only,OP_HAS_NOUNS,BioTop,Yes-No-2-part-1-rel+1-quant-only.csv,yn2p1r1_1_qo,has_nouns
27978,[X] SubclassOf([prop] some [Y]),Universe SubclassOf(hasParticipant some Compound),Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does universe have a participant that is a com...,Yes-No-2-part-1-rel,OP_HAS_NOUNS,BioTop,Yes-No-2-part-1-rel.csv,yn2p1r,has_nouns

question_type
Yes-No-2-part-1-rel                 20562
Yes-No-2-part-1-rel+1-quant-only    18480
What-1-part-1-rel                    6854
What-2-part-1-rel                    6854
What-2-part-1-rel-quant-only         6160
Yes-No-2-part-1-rel+1-quant-some     2082
What-2-part-1-rel-quant-some          694
Definition                            149
Name: count, dtype: int64

remove ontologies

In [ ]:
print(df['ontology'].unique())
n_rows1 = df.shape[0]

remove_ontologies = ["MFOEM", "bcio", "exmo", "swo"]
df[df.ontology.isin(remove_ontologies)].groupby("ontology").sample(3)

df_filtered = df[~df.ontology.isin(remove_ontologies)]
print(df_filtered.shape)
df_filtered.to_csv("../dataset/qgenllm-updated-2-filtered.csv", sep=";", index=False)
n_rows2 = df_filtered.shape[0]
print(f"Removed {n_rows1 - n_rows2} rows.")

display(df_filtered[df_filtered.ontology == "BioTop"].sample(5))

['AWO' 'bcio' 'BioTop' 'CopyrightAll' 'Cultural-On' 'exmo' 'MFOEM' 'olia'
 'Pizza' 'Stuff' 'swo']
(489143, 10)
Removed 24842 rows.

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short
2436,[X] SubclassOf([prop] some [Y]),Universe SubclassOf(isRealizationOf some Immat...,What is [X] [prop/*OP_IS_NOUNS_PREP]?,What is universe a realization of?,What-1-part-1-rel,OP_IS_NOUNS_PREP,BioTop,What-1-part-1-rel.csv,w1p1r,is_noun_prep
8652,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] some...","Universe SubclassOf(Condition),Universe Subcla...",Which [X/noArticle] is [prop/*OP_IS_PAST_PARTI...,Which condition is preceded by a value region?,What-2-part-1-rel,OP_IS_PAST_PARTICIPLE_BY,BioTop,What-2-part-1-rel.csv,w2p1r,is_pp_b
15931,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] some...","Universe SubclassOf(Condition),Universe Subcla...",Which [X/noArticle] [prop/*OP_HAS_NOUNS-third]...,Which condition has an outcome that is only an...,What-2-part-1-rel-quant-only,OP_HAS_NOUNS,BioTop,What-2-part-1-rel-quant-only.csv,w2p1r_qo,has_nouns
15553,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] some...","Universe SubclassOf(Condition),Universe Subcla...",Which [X/noArticle] [prop/*OP_VERB-third] only...,Which condition precedes only quality?,What-2-part-1-rel-quant-only,OP_VERB,BioTop,What-2-part-1-rel-quant-only.csv,w2p1r_qo,verb
58617,[X] SubclassOf([prop] some [Y]),Cell SubclassOf(isLifeOf some TaxonQuality),Is [X] [prop/*OP_IS_NOUNS_PREP] only [Y]?,Is a cell life of only a taxon quality?,Yes-No-2-part-1-rel+1-quant-only,OP_IS_NOUNS_PREP,BioTop,Yes-No-2-part-1-rel+1-quant-only.csv,yn2p1r1_1_qo,is_noun_prep

remove question type with just a handful of examples

In [ ]:

# for each ontology, remove all the question type with less than N_MIN examples
N_MIN = 10
df_final = pd.DataFrame()
dfs = []

print(f"Removing question types with < {N_MIN} examples - per ontology")

for ontology, group in df_filtered.groupby("ontology"):
    print()
    print(ontology)
    counts = group['question_type'].value_counts()
    to_keep = counts[counts >= N_MIN].index
    remove_qt = counts[counts < N_MIN].index

    print("KEEPING:", list(to_keep))
    print("REMOVING:", list(remove_qt))
    print(f"Ontology: {ontology}")
    print(f"  Removing question types: {list(remove_qt)}")
    
    df_ontology_filtered = group[group['question_type'].isin(to_keep)]
    dfs.append(df_ontology_filtered)
    print(f"Ontology {ontology}: {group.shape[0]} -> {df_ontology_filtered.shape[0]} rows")
df_final = pd.concat(dfs)

df_final = df_final.sort_values(by=["ontology", "question_type"]).reset_index(drop=True)
df_final["row_id"] = list(range(len(df_final)))


n_rows3 = df_final.shape[0]
print(f"Removed {n_rows2 - n_rows3} rows due to few examples per question type.")

# This is the dataset used for the experiments
df_final.to_csv("../dataset/qgenllm-updated-2-filtered-min_q.csv", sep=";", index=False)

Removing question types with < 10 examples - per ontology

AWO
KEEPING: ['op_Yes-No-2-part-1-rel', 'op_Yes-No-2-part-1-rel+1-quant-some', 'op_What-2-part-1-rel', 'op_What-2-part-1-rel-quant-some', 'op_What-1-part-1-rel', 'op_Yes-No-2-part-1-rel+1-quant-only', 'Definition', 'op_What-2-part-1-rel-quant-only']
REMOVING: []
Ontology: AWO
  Removing question types: []
Ontology AWO: 1153 -> 1153 rows

BioTop
KEEPING: ['Yes-No-2-part-1-rel', 'Yes-No-2-part-1-rel+1-quant-only', 'What-1-part-1-rel', 'What-2-part-1-rel', 'What-2-part-1-rel-quant-only', 'Yes-No-2-part-1-rel+1-quant-some', 'What-2-part-1-rel-quant-some', 'Definition']
REMOVING: []
Ontology: BioTop
  Removing question types: []
Ontology BioTop: 61835 -> 61835 rows

CopyrightAll
KEEPING: ['op_Yes-No-2-part-1-rel', 'op_What-2-part-1-rel', 'op_Yes-No-2-part-1-rel+1-quant-only', 'op_What-2-part-1-rel-quant-only', 'op_What-1-part-1-rel', 'op_What-2-part-1-rel-quant-some']
REMOVING: ['op_Yes-No-2-part-1-rel+1-quant-some']
Ontology: CopyrightAll
  Removing question types: ['op_Yes-No-2-part-1-rel+1-quant-some']
Ontology CopyrightAll: 302 -> 293 rows

Cultural-On
KEEPING: ['op_Yes-No-2-part-1-rel', 'op_Yes-No-2-part-1-rel+1-quant-only', 'op_What-1-part-1-rel', 'op_What-2-part-1-rel', 'op_What-2-part-1-rel-quant-only', 'op_Yes-No-2-part-1-rel+1-quant-some', 'op_What-2-part-1-rel-quant-some', 'Definition']
REMOVING: []
Ontology: Cultural-On
  Removing question types: []
Ontology Cultural-On: 22668 -> 22668 rows

Pizza
KEEPING: ['op_What-2-part-1-rel', 'op_Yes-No-2-part-1-rel', 'op_Yes-No-2-part-1-rel+1-quant-only', 'op_What-2-part-1-rel-quant-only', 'op_What-1-part-1-rel', 'op_What-2-part-1-rel-quant-some', 'op_Yes-No-2-part-1-rel+1-quant-some', 'Definition']
REMOVING: []
Ontology: Pizza
  Removing question types: []
Ontology Pizza: 62701 -> 62701 rows

Stuff
KEEPING: ['op_Yes-No-2-part-1-rel', 'op_Yes-No-2-part-1-rel+1-quant-only', 'op_What-2-part-1-rel', 'op_What-2-part-1-rel-quant-only', 'op_What-1-part-1-rel', 'op_What-2-part-1-rel-quant-some', 'op_Yes-No-2-part-1-rel+1-quant-some', 'Definition']
REMOVING: []
Ontology: Stuff
  Removing question types: []
Ontology Stuff: 340412 -> 340412 rows

olia
KEEPING: ['op_What-2-part-1-rel-quant-some', 'op_What-2-part-1-rel', 'op_Yes-No-2-part-1-rel+1-quant-some', 'op_Yes-No-2-part-1-rel']
REMOVING: ['op_What-1-part-1-rel']
Ontology: olia
  Removing question types: ['op_What-1-part-1-rel']
Ontology olia: 72 -> 68 rows
Removed 13 rows due to few examples per question type.

FILTERED DATASET

In [ ]:
import pandas as pd

df = pd.read_csv("../dataset/qgenllm-updated-2-filtered-min_q.csv", sep=";")
print("ONTOLOGIES")
print(df.ontology.unique())

display( df.groupby(["ontology", "question_type"]).size() )
# display the pairs (ontology, question_type) that have less than 10 samples
counts = df.groupby(["ontology", "question_type"]).size()
with pd.option_context("display.max_rows", None):
    display( counts[counts < 10] )
    assert counts[counts < 10].shape[0] == 0, "failed"

ONTOLOGIES
['AWO' 'BioTop' 'CopyrightAll' 'Cultural-On' 'Pizza' 'Stuff' 'olia']

ontology      question_type
AWO           Definition                                69
              op_What-1-part-1-rel                     100
              op_What-2-part-1-rel                     192
              op_What-2-part-1-rel-quant-only           58
              op_What-2-part-1-rel-quant-some          134
              op_Yes-No-2-part-1-rel                   300
              op_Yes-No-2-part-1-rel+1-quant-only       72
              op_Yes-No-2-part-1-rel+1-quant-some      228
BioTop        Definition                               149
CopyrightAll  op_What-1-part-1-rel                      24
              op_What-2-part-1-rel                      67
              op_What-2-part-1-rel-quant-only           55
              op_What-2-part-1-rel-quant-some           12
              op_Yes-No-2-part-1-rel                    72
              op_Yes-No-2-part-1-rel+1-quant-only       63
Cultural-On   Definition                                33
              op_What-1-part-1-rel                    2769
              op_What-2-part-1-rel                    1626
              op_What-2-part-1-rel-quant-only         1584
              op_What-2-part-1-rel-quant-some           42
              op_Yes-No-2-part-1-rel                  8307
              op_Yes-No-2-part-1-rel+1-quant-only     8208
              op_Yes-No-2-part-1-rel+1-quant-some       99
Pizza         Definition                               499
              op_What-1-part-1-rel                    4492
              op_What-2-part-1-rel                   15379
              op_What-2-part-1-rel-quant-only        11125
              op_What-2-part-1-rel-quant-some         4254
              op_Yes-No-2-part-1-rel                 13476
              op_Yes-No-2-part-1-rel+1-quant-only    11682
              op_Yes-No-2-part-1-rel+1-quant-some     1794
Stuff         Definition                               174
              op_What-1-part-1-rel                   25306
              op_What-2-part-1-rel                   74567
              op_What-2-part-1-rel-quant-only        72249
              op_What-2-part-1-rel-quant-some         2318
              op_Yes-No-2-part-1-rel                 82899
              op_Yes-No-2-part-1-rel+1-quant-only    81501
              op_Yes-No-2-part-1-rel+1-quant-some     1398
olia          op_What-2-part-1-rel                      22
              op_What-2-part-1-rel-quant-some           22
              op_Yes-No-2-part-1-rel                    12
              op_Yes-No-2-part-1-rel+1-quant-some       12
dtype: int64

Series([], dtype: int64)

## actual dataset
Prepare a dataframe with 10 questions per question type for every ontology

Fix a seed then select

In [5]:
seed = 123

df_questions = df.groupby(["ontology", "question_type"]).sample(n=10, random_state=seed)
print(df_questions.shape)

print("SAMPLE")
display(df_questions.sample(20))
print("ONTOLOGIES")
print(df_questions.ontology.unique())
for ontology, gdf in df_questions.groupby("ontology"):
    print(f"Ontology: {ontology}")
    print(f"Question types: {gdf['question_type'].unique()}")
    print(f"N question types: {gdf['question_type'].nunique()}")
    print(f"Total questions: {gdf.shape[0]}")
    print(10 * "-")

df_questions.to_csv(f"../dataset/qgenllm-ds-seed-{seed}.csv", sep=";", index=False)

(430, 11)
SAMPLE

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short,question_id
74172,[X] SubclassOf([prop] only [Y]),NonVegetarianPizza SubclassOf(hasBase only Piz...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does a non vegetarian pizza have a base that i...,op_Yes-No-2-part-1-rel+1-quant-only,OP_HAS_NOUNS,Pizza,Yes-No-2-part-1-rel+1-quant-only.csv,yn2p1r1_1_qo,has_nouns,74172
48271,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] only...","Hot SubclassOf(hasBase only ValuePartition),Ho...",Which [X/noArticle] [prop/*OP_HAS_NOUNS-third]...,Which value partition has a base that is only ...,op_What-2-part-1-rel-quant-only,OP_HAS_NOUNS,Pizza,What-2-part-1-rel-quant-only.csv,w2p1r_qo,has_nouns,48271
1467,[X] SubclassOf([prop] only [Y]),Broadcast SubclassOf(result only BroadcastEvent),[X] [prop/*OP_VERB-third] [Y]. True or false?,A broadcast results a broadcast event. True or...,op_Yes-No-2-part-1-rel,OP_VERB,CopyrightAll,Yes-No-2-part-1-rel.csv,yn2p1r,verb,1467
846,[X] SubclassOf([prop] only [Y]),Camelopard SubclassOf(Live-on only Habitat),True or false: [X] [prop/*OP_VERB_PREP-third] ...,True or false: A camelopard lives on a habitat.,op_Yes-No-2-part-1-rel,OP_VERB_PREP,AWO,Yes-No-2-part-1-rel.csv,yn2p1r,verb_prep,846
401009,[X] SubclassOf([prop] only [Y]),AbstractRegion SubclassOf(hasGranuleType only ...,True or false: [X] [prop/*OP_HAS_NOUNS-third] ...,True or false: An abstract region has a granul...,op_Yes-No-2-part-1-rel+1-quant-only,OP_HAS_NOUNS,Stuff,Yes-No-2-part-1-rel+1-quant-only.csv,yn2p1r1_1_qo,has_nouns,401009
2159,[X] SubclassOf([prop] only [Y]),DayOfWeek SubclassOf(isRoleIn only RoleInTime),What is [X] [prop/*OP_IS_NOUNS_PREP]?,What is a day of the week a role in?,op_What-1-part-1-rel,OP_IS_NOUNS_PREP,Cultural-On,What-1-part-1-rel.csv,w1p1r,is_noun_prep,2159
71448,[X] SubclassOf([prop] only [Y]),Spiciness SubclassOf(isBaseOf only Medium),True or false: [X] is [prop/*OP_IS_NOUNS_PREP]...,True or false: A spiciness is a base of a medium.,op_Yes-No-2-part-1-rel,OP_IS_NOUNS_PREP,Pizza,Yes-No-2-part-1-rel.csv,yn2p1r,is_noun_prep,71448
427433,[X] SubclassOf([prop] some [Y]),ImpersonalVerb SubclassOf(hasSemanticValency s...,[X] [prop/*OP_HAS_NOUNS-third] that is some [Y...,An impersonal verb has a semantic valency that...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427433
259769,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] some...",SolidHeterogeneousMixture SubclassOf(hasPart s...,Which [X/noArticle] [prop/*OP_HAS_NOUNS-third]...,Which physical endurant has part that is some ...,op_What-2-part-1-rel-quant-some,OP_HAS_NOUNS,Stuff,What-2-part-1-rel-quant-some.csv,w2p1r_qs,has_nouns,259769
49383,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] only...",American SubclassOf(hasSpiciness only Spicines...,Which [X/noArticle] [prop/*OP_HAS_NOUNS-third]...,Which interesting pizza has a spiciness that i...,op_What-2-part-1-rel-quant-only,OP_HAS_NOUNS,Pizza,What-2-part-1-rel-quant-only.csv,w2p1r_qo,has_nouns,49383
1603,[X] SubclassOf([Y]),TemporaryClosure SubclassOf(AccessCondition),What is [X]?,What is a temporary closure?,Definition,OP_DEFINITION,Cultural-On,Definition.csv,def,definition,1603
1274,[X] SubclassOf([Y]),TwoDimensionalPhysicalEntity SubclassOf(Immate...,What is [X]?,What is a two dimensional physical entity?,Definition,OP_DEFINITION,BioTop,Definition.csv,def,definition,1274
49880,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] only...",Spiciness SubclassOf(isIngredientOf only Quatt...,Which [X/noArticle] is [prop/*OP_IS_NOUNS_PREP...,Which value partition is an ingredient of only...,op_What-2-part-1-rel-quant-only,OP_IS_NOUNS_PREP,Pizza,What-2-part-1-rel-quant-only.csv,w2p1r_qo,is_noun_prep,49880
259544,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] some...",LiquidAerosol SubclassOf(hasPartStuff some End...,Which [X/noArticle] [prop/*OP_HAS_NOUNS-third]...,Which mixed stuff has part stuff that is some ...,op_What-2-part-1-rel-quant-some,OP_HAS_NOUNS,Stuff,What-2-part-1-rel-quant-some.csv,w2p1r_qs,has_nouns,259544
87109,[X] SubclassOf([Y]),SolidSol SubclassOf(Stuff),What is [X]?,What is a solid sol?,Definition,OP_DEFINITION,Stuff,Definition.csv,def,definition,87109
427432,[X] SubclassOf([prop] some [Y]),ImpersonalVerb SubclassOf(hasSemanticValency s...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does an impersonal verb have a semantic valenc...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427432
502,"[Z] SubclassOf([X]),[Z] SubclassOf([prop] some...","Impala SubclassOf(Participate-In some Loop),Im...",Which [X/noArticle] [prop/*OP_VERB_PREP-third]...,Which animal participates in some being a loop?,op_What-2-part-1-rel-quant-some,OP_VERB_PREP,AWO,What-2-part-1-rel-quant-some.csv,w2p1r_qs,verb_prep,502
7240,[Z] SubclassOf([prop] only [Y]),NewsArticle SubclassOf(isSubjectOf only Creati...,Which [X/noArticle] is [prop/*OP_IS_NOUNS_PREP...,Which creative work is a subject of only creat...,op_What-2-part-1-rel-quant-only,OP_IS_NOUNS_PREP,Cultural-On,What-2-part-1-rel-quant-only.csv,w2p1r_qo,is_noun_prep,7240
785,[X] SubclassOf([prop] only [Y]),King-of-beasts SubclassOf(eats only Animal),Does [X] [prop/*OP_VERB-infinitive] [Y]?,Does a king of beasts eat an animal?,op_Yes-No-2-part-1-rel,OP_VERB,AWO,Yes-No-2-part-1-rel.csv,yn2p1r,verb,785
24431,[X] SubclassOf([Y]),FourCheesesTopping SubclassOf(CheeseTopping),What is [X]?,What is a four cheeses topping?,Definition,OP_DEFINITION,Pizza,Definition.csv,def,definition,24431

ONTOLOGIES
['AWO' 'BioTop' 'CopyrightAll' 'Cultural-On' 'Pizza' 'Stuff' 'olia']
Ontology: AWO
Question types: ['Definition' 'op_What-1-part-1-rel' 'op_What-2-part-1-rel'
 'op_What-2-part-1-rel-quant-only' 'op_What-2-part-1-rel-quant-some'
 'op_Yes-No-2-part-1-rel' 'op_Yes-No-2-part-1-rel+1-quant-only'
 'op_Yes-No-2-part-1-rel+1-quant-some']
N question types: 8
Total questions: 80
----------
Ontology: BioTop
Question types: ['Definition']
N question types: 1
Total questions: 10
----------
Ontology: CopyrightAll
Question types: ['op_What-1-part-1-rel' 'op_What-2-part-1-rel'
 'op_What-2-part-1-rel-quant-only' 'op_What-2-part-1-rel-quant-some'
 'op_Yes-No-2-part-1-rel' 'op_Yes-No-2-part-1-rel+1-quant-only']
N question types: 6
Total questions: 60
----------
Ontology: Cultural-On
Question types: ['Definition' 'op_What-1-part-1-rel' 'op_What-2-part-1-rel'
 'op_What-2-part-1-rel-quant-only' 'op_What-2-part-1-rel-quant-some'
 'op_Yes-No-2-part-1-rel' 'op_Yes-No-2-part-1-rel+1-quant-only'
 'op_Yes-No-2-part-1-rel+1-quant-some']
N question types: 8
Total questions: 80
----------
Ontology: Pizza
Question types: ['Definition' 'op_What-1-part-1-rel' 'op_What-2-part-1-rel'
 'op_What-2-part-1-rel-quant-only' 'op_What-2-part-1-rel-quant-some'
 'op_Yes-No-2-part-1-rel' 'op_Yes-No-2-part-1-rel+1-quant-only'
 'op_Yes-No-2-part-1-rel+1-quant-some']
N question types: 8
Total questions: 80
----------
Ontology: Stuff
Question types: ['Definition' 'op_What-1-part-1-rel' 'op_What-2-part-1-rel'
 'op_What-2-part-1-rel-quant-only' 'op_What-2-part-1-rel-quant-some'
 'op_Yes-No-2-part-1-rel' 'op_Yes-No-2-part-1-rel+1-quant-only'
 'op_Yes-No-2-part-1-rel+1-quant-some']
N question types: 8
Total questions: 80
----------
Ontology: olia
Question types: ['op_What-2-part-1-rel' 'op_What-2-part-1-rel-quant-some'
 'op_Yes-No-2-part-1-rel' 'op_Yes-No-2-part-1-rel+1-quant-some']
N question types: 4
Total questions: 40
----------

READ DF_QUESTIONS

THEN SELECT THE ONTOLOGIES FOR THE FEW-SHOT EXAMPLES

For each row, we select the ontologies from which we will sample the questions. For each row, the selected ontology WILL NOT include the ontology in the row (held-out, used as test).

First, each ontology is selected. Then K-(available ontologies with the same question type) are sampled with replacement.

The ontologies are SHUFFLED using the seed in the filename, MEANING THAT THEY WILL NOT APPEAR IN THE SAME ORDER.

In [ ]:
import pandas as pd
import numpy as np

filename = "../dataset/qgenllm-ds-seed-123.csv"
# get the seed from the filename
seed = int(filename.split("-")[-1].split(".")[0])
print("seed:", seed)
df = pd.read_csv(filename, sep=";").reset_index(drop=True)

print("shape:", df.shape)
print("SAMPLE")
display(df.head(20))

# build dictionary: question_type -> list of ontologies that have that question type
qt2onto = {}
for qt, gdf in df.groupby("question_type"):
    ontologies = gdf['ontology'].unique().tolist()
    qt2onto[qt] = ontologies

for k, v in qt2onto.items():
    print(f"Question type: {k}")
    print(f"  Ontologies: {v}")

rng = np.random.default_rng(seed)
df["seed"] = rng.integers(0, 2**32-1, size=df.shape[0])


# prepare a list of up to MAX_FEW_SHOTS

MAX_FEW_SHOTS = 10

def select_ontos(row):
    qt = row["question_type"]
    # select other ontos by removing the ontology in the current row
    other_ontos = [o for o in qt2onto[qt] if o != row["ontology"]]
    rng = np.random.default_rng(row["seed"])
    # shuffle other_ontos
    other_ontos = rng.permutation(other_ontos)
    # now sample with replacement up to MAX_FEW_SHOTS
    remaining_ontos = rng.choice(other_ontos, size=MAX_FEW_SHOTS-len(other_ontos), replace=True)
    selected_ontos = list(other_ontos) + list(remaining_ontos)
    return selected_ontos

df["q_from_os"] = df.apply(select_ontos, axis=1)

display(df)

seed: 123
shape: (430, 11)
SAMPLE

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short,question_id
0,[X] SubclassOf([Y]),Grass SubclassOf(Plant),What is [X]?,What is grass?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,8
1,[X] SubclassOf([Y]),Impala SubclassOf(TerrestrialAnimal),What is [X]?,What is an impala?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,37
2,[X] SubclassOf([Y]),Camelopard SubclassOf(Animal),What is [X]?,What is a camelopard?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,40
3,[X] EquivalentTo([A]),Gras EquivalentTo(Grass),What is [X]?,What is a gras?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,56
4,[X] SubclassOf([Y]),Warthog SubclassOf(Animal),What is [X]?,What is a warthog?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,23
5,[X] EquivalentTo([A]),BumbleBee EquivalentTo(HumbleBee),What is [X]?,What is a bumble bee?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,53
6,[X] SubclassOf([Y]),Gras SubclassOf(Plant),What is [X]?,What is a gras?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,9
7,[X] SubclassOf([Y]),Phloem SubclassOf(PlantParts),What is [X]?,What is phloem?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,43
8,[X] EquivalentTo([A]),Loop EquivalentTo(Walk),What is [X]?,What is being a loop?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,68
9,[X] SubclassOf([Y]),BumbleBee SubclassOf(Insect),What is [X]?,What is a bumble bee?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,1
10,[X] SubclassOf([prop] some [Y]),Tasty-plant SubclassOf(eaten-by some Carnivore),What is [X] is [prop/*OP_IS_PAST_PARTICIPLE_BY]?,What is a tasty plant is eaten by?,op_What-1-part-1-rel,OP_IS_PAST_PARTICIPLE_BY,AWO,What-1-part-1-rel.csv,w1p1r,is_pp_b,142
11,[X] SubclassOf([prop] only [Y]),Camelopard SubclassOf(Live-on only Habitat),What does [X] [prop/*OP_VERB_PREP-infinitive]?,What does a camelopard live on?,op_What-1-part-1-rel,OP_VERB_PREP,AWO,What-1-part-1-rel.csv,w1p1r,verb_prep,162
12,[X] SubclassOf([prop] some [Y]),Elephant SubclassOf(Participate-In some Loop),What does [X] [prop/*OP_VERB_PREP-infinitive]?,What does an elephant participate in?,op_What-1-part-1-rel,OP_VERB_PREP,AWO,What-1-part-1-rel.csv,w1p1r,verb_prep,100
13,[X] SubclassOf([prop] only [Y]),Elephant SubclassOf(Live-on only Land),What does [X] [prop/*OP_VERB_PREP-infinitive]?,What does an elephant live on?,op_What-1-part-1-rel,OP_VERB_PREP,AWO,What-1-part-1-rel.csv,w1p1r,verb_prep,157
14,[X] SubclassOf([prop] some [Y]),Phloem SubclassOf(proper-part-of some PlantParts),What is [X] [prop/*OP_IS_NOUNS_PREP]?,What is phloem proper part of?,op_What-1-part-1-rel,OP_IS_NOUNS_PREP,AWO,What-1-part-1-rel.csv,w1p1r,is_noun_prep,137
15,[X] SubclassOf([prop] only [Y]),Impala SubclassOf(Live-on only Land),What does [X] [prop/*OP_VERB_PREP-infinitive]?,What does an impala live on?,op_What-1-part-1-rel,OP_VERB_PREP,AWO,What-1-part-1-rel.csv,w1p1r,verb_prep,159
16,[X] SubclassOf([prop] some [Y]),Xylem SubclassOf(proper-part-of some Plant),What is [X] [prop/*OP_IS_NOUNS_PREP]?,What is xylem proper part of?,op_What-1-part-1-rel,OP_IS_NOUNS_PREP,AWO,What-1-part-1-rel.csv,w1p1r,is_noun_prep,110
17,[X] SubclassOf([prop] only [Y]),King-of-beasts SubclassOf(Live-on only Habitat),What does [X] [prop/*OP_VERB_PREP-infinitive]?,What does a king of beasts live on?,op_What-1-part-1-rel,OP_VERB_PREP,AWO,What-1-part-1-rel.csv,w1p1r,verb_prep,168
18,[X] SubclassOf([prop] only [Y]),Warthog SubclassOf(Live-on only Land),What does [X] [prop/*OP_VERB_PREP-infinitive]?,What does a warthog live on?,op_What-1-part-1-rel,OP_VERB_PREP,AWO,What-1-part-1-rel.csv,w1p1r,verb_prep,153
19,[X] SubclassOf([prop] some [Y]),Warthog SubclassOf(eats some Gras),What does [X] [prop/*OP_VERB-infinitive]?,What does a warthog eat?,op_What-1-part-1-rel,OP_VERB,AWO,What-1-part-1-rel.csv,w1p1r,verb,71

Question type: Definition
  Ontologies: ['AWO', 'BioTop', 'Cultural-On', 'Pizza', 'Stuff']
Question type: op_What-1-part-1-rel
  Ontologies: ['AWO', 'CopyrightAll', 'Cultural-On', 'Pizza', 'Stuff']
Question type: op_What-2-part-1-rel
  Ontologies: ['AWO', 'CopyrightAll', 'Cultural-On', 'Pizza', 'Stuff', 'olia']
Question type: op_What-2-part-1-rel-quant-only
  Ontologies: ['AWO', 'CopyrightAll', 'Cultural-On', 'Pizza', 'Stuff']
Question type: op_What-2-part-1-rel-quant-some
  Ontologies: ['AWO', 'CopyrightAll', 'Cultural-On', 'Pizza', 'Stuff', 'olia']
Question type: op_Yes-No-2-part-1-rel
  Ontologies: ['AWO', 'CopyrightAll', 'Cultural-On', 'Pizza', 'Stuff', 'olia']
Question type: op_Yes-No-2-part-1-rel+1-quant-only
  Ontologies: ['AWO', 'CopyrightAll', 'Cultural-On', 'Pizza', 'Stuff']
Question type: op_Yes-No-2-part-1-rel+1-quant-some
  Ontologies: ['AWO', 'Cultural-On', 'Pizza', 'Stuff', 'olia']

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short,question_id,seed,q_from_os
0,[X] SubclassOf([Y]),Grass SubclassOf(Plant),What is [X]?,What is grass?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,8,66316748,"[BioTop, Pizza, Stuff, Cultural-On, Cultural-O..."
1,[X] SubclassOf([Y]),Impala SubclassOf(TerrestrialAnimal),What is [X]?,What is an impala?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,37,2930678936,"[Cultural-On, Stuff, BioTop, Pizza, Pizza, Cul..."
2,[X] SubclassOf([Y]),Camelopard SubclassOf(Animal),What is [X]?,What is a camelopard?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,40,2546691362,"[Pizza, Cultural-On, Stuff, BioTop, Pizza, Bio..."
3,[X] EquivalentTo([A]),Gras EquivalentTo(Grass),What is [X]?,What is a gras?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,56,231159514,"[Stuff, BioTop, Cultural-On, Pizza, Pizza, Piz..."
4,[X] SubclassOf([Y]),Warthog SubclassOf(Animal),What is [X]?,What is a warthog?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,23,3904498325,"[BioTop, Stuff, Cultural-On, Pizza, Stuff, Stu..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,[X] SubclassOf([prop] some [Y]),hasWordConjunct SubclassOf(hasChild some Token),True or false: [X] [prop/*OP_HAS_NOUNS-third] ...,True or false: A has word conjunct has a child...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427443,1569547285,"[Pizza, AWO, Cultural-On, Stuff, AWO, AWO, AWO..."
426,[X] SubclassOf([prop] some [Y]),hasConjunct SubclassOf(hasParent some Coordina...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does a has conjunct have a parent that is some...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427438,1921824982,"[Cultural-On, Pizza, Stuff, AWO, Pizza, AWO, S..."
427,[X] SubclassOf([prop] some [Y]),NonspecificPronoun SubclassOf(hasSpecificity s...,[X] [prop/*OP_HAS_NOUNS-third] that is some [Y...,A nonspecific pronoun has a specificity that i...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427436,2951387684,"[Stuff, Pizza, Cultural-On, AWO, AWO, Pizza, S..."
428,[X] SubclassOf([prop] some [Y]),hasWordConjunct SubclassOf(hasChild some Token),[X] [prop/*OP_HAS_NOUNS-third] that is some [Y...,A has word conjunct has a child that is some t...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427442,2979572471,"[Stuff, AWO, Cultural-On, Pizza, Cultural-On, ..."
429,[X] SubclassOf([prop] some [Y]),NonspecificPronoun SubclassOf(hasSpecificity s...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does a nonspecific pronoun have a specificity ...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427435,3158202469,"[Cultural-On, Stuff, AWO, Pizza, AWO, Cultural..."

Now select the questions using the list of ontologies built in the previous step and stored in the column `q_from_os`

The selection

In [ ]:



def select_questions(dataset):
    def sample_questions(row):
        qt = row["question_type"]
        used_qs = []
        qs = []
        axioms = []
        for o in row["q_from_os"]:
            iii = (dataset.ontology == o) & (dataset.question_type == qt) & (~dataset.row_id.isin(used_qs))
            available_qs = dataset[iii]
            if available_qs.shape[0] == 0:
                assert False, f"No available questions for ontology {o} and question type {qt}"
            # sample one question randomly
            sampled_q = available_qs.sample(n=1, random_state=row["seed"])
            qs.append(sampled_q.iloc[0]["question"])
            used_qs.append(sampled_q.iloc[0]["row_id"])
            axioms.append(sampled_q.iloc[0]["axiom"])
        return axioms, qs
    dataset["sample_axioms"], dataset["sample_questions"] = zip(*dataset.apply(sample_questions, axis=1))
    return dataset

df = select_questions(df)

In [8]:
display(df.loc[:, ["sample_questions", "sample_axioms"]])

iii = [100, 150, 200]
for i in iii:
    questions = df.iloc[i]["sample_questions"]
    axioms = df.iloc[i]["sample_axioms"]
    for q, a in zip(questions, axioms):
        print(f"A: {a}")
        print(f"Q: {q}")
        print("-----")

,sample_questions,sample_axioms
0,"[What is universe?, What is a thin and crispy ...","[Universe SubclassOf(Condition), ThinAndCrispy..."
1,"[What is a cultural institute or site?, What i...",[CulturalInstituteOrSite SubclassOf(CulturalEn...
2,"[What is a soho?, What is a monumental area or...","[Soho SubclassOf(VegetarianPizzaEquivalent1), ..."
3,"[What is a micellar colloid?, What is canonici...","[MicellarColloid SubclassOf(MixedStuff), Canon..."
4,"[What is a noncanonical value region?, What is...",[NoncanonicalValueRegion SubclassOf(ValueRegio...
...,...,...
425,[True or false: A mozzarella topping has a spi...,[MozzarellaTopping SubclassOf(hasSpiciness som...
426,[Does a cultural institute or site have a site...,[CulturalInstituteOrSite SubclassOf(hasSite so...
427,[Is a piece proper part of some amount of stuf...,[Piece SubclassOf(properPartOf some AmountOfSt...
428,[A solution has part that is some physical end...,[Solution SubclassOf(hasPart some PhysicalEndu...
429,[A holder of archives has a type that is some ...,[HolderOfArchive SubclassOf(hasCISType some CI...

A: DispersedPhase SubclassOf(hasState only PureStuff),DispersedPhase SubclassOf(Role)
Q: Which role has a state that is pure stuff?
-----
A: ArchaeologicalArea SubclassOf(hasMember only CulturalEntity),ArchaeologicalArea SubclassOf(CulturalInstituteOrSite)
Q: Which cultural institute or site has a member that is a cultural entity?
-----
A: hasWordConjunct SubclassOf(hasConjunct),hasWordConjunct SubclassOf(hasChild some Token)
Q: Which has conjunct has a child that is a token?
-----
A: FourSeasons SubclassOf(hasIngredient some AnchoviesTopping),FourSeasons SubclassOf(InterestingPizza)
Q: Which interesting pizza has an ingredient that is an anchovies topping?
-----
A: Warthog SubclassOf(Live-on only Habitat),Warthog SubclassOf(Animal)
Q: Which animal lives on a habitat?
-----
A: Impala SubclassOf(Live-on only Habitat),Impala SubclassOf(Animal)
Q: Which animal lives on a habitat?
-----
A: Gas SubclassOf(hasContainedScatteredPortion only DispersionColloid),Gas SubclassOf(State)
Q: Which state has a contained scattered portion that is a dispersion colloid?
-----
A: BumbleBee SubclassOf(Participate-In some Hole-up),BumbleBee SubclassOf(Animal)
Q: Which animal participates in holing up?
-----
A: Giardiniera SubclassOf(hasSpiciness only Spiciness),Giardiniera SubclassOf(DomainConcept)
Q: Which domain thing has a spiciness that is a spiciness?
-----
A: Cinema SubclassOf(hasNameInTime only NameInTime),Cinema SubclassOf(CulturalEntity)
Q: Which cultural entity has a name in time that is a name in time?
-----
A: Warthog SubclassOf(Animal)
Q: What is a warthog?
-----
A: NoncanonicalValueRegion SubclassOf(ValueRegion)
Q: What is a noncanonical value region?
-----
A: Soho SubclassOf(VegetarianPizzaEquivalent1)
Q: What is a soho?
-----
A: ContinuousMedium SubclassOf(Role)
Q: What is a continuous medium?
-----
A: AmericanHot SubclassOf(Food)
Q: What is an american hot?
-----
A: Loop EquivalentTo(Walk)
Q: What is being a loop?
-----
A: MicellarColloid SubclassOf(MixedStuff)
Q: What is a micellar colloid?
-----
A: PizzaTopping SubclassOf(Food)
Q: What is a pizza topping?
-----
A: PrinceCarlo SubclassOf(NamedPizza)
Q: What is a prince carlo?
-----
A: Canonicity SubclassOf(Particular)
Q: What is canonicity?
-----
A: Drop SubclassOf(hasQuale only SolidFoam)
Q: True or false: A drop has a quale that is a solid foam.
-----
A: Broadcast SubclassOf(result only BroadcastEvent)
Q: Does a broadcast result a broadcast event?
-----
A: Phloem SubclassOf(part-of some Stem)
Q: True or false: Phloem is part of a stem.
-----
A: Medium SubclassOf(isIngredientOf only LeekTopping)
Q: Is a medium an ingredient of a leek topping?
-----
A: hasWordConjunct SubclassOf(hasChild some Token)
Q: Does a has word conjunct have a child that is a token?
-----
A: ContinuousMedium SubclassOf(hasGranuleType only Sol)
Q: Does a continuous medium have a granule type that is a sol?
-----
A: Ion SubclassOf(hasPortion only Atom)
Q: An ion has a portion that is an atom. True or false?
-----
A: State SubclassOf(scatteredStuffPartOf only AmountOfStuff)
Q: Stating is scattered stuff part of an amount of stuff. True or false?
-----
A: State SubclassOf(inheresIn only Portion)
Q: True or false: Stating inheres in a portion.
-----
A: AnchoviesTopping SubclassOf(hasSpiciness some ValuePartition)
Q: True or false: An anchovies topping has a spiciness that is a value partition.
-----

Check columns and save dataset

In [9]:
display(df)

df.to_parquet(
    f"../dataset/qgenllm-ds-seed-{seed}-few-shots.parquet",
    engine="pyarrow",
    index=False,
)

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short,question_id,seed,q_from_os,sample_axioms,sample_questions
0,[X] SubclassOf([Y]),Grass SubclassOf(Plant),What is [X]?,What is grass?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,8,66316748,"[BioTop, Pizza, Stuff, Cultural-On, Cultural-O...","[Universe SubclassOf(Condition), ThinAndCrispy...","[What is universe?, What is a thin and crispy ..."
1,[X] SubclassOf([Y]),Impala SubclassOf(TerrestrialAnimal),What is [X]?,What is an impala?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,37,2930678936,"[Cultural-On, Stuff, BioTop, Pizza, Pizza, Cul...",[CulturalInstituteOrSite SubclassOf(CulturalEn...,"[What is a cultural institute or site?, What i..."
2,[X] SubclassOf([Y]),Camelopard SubclassOf(Animal),What is [X]?,What is a camelopard?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,40,2546691362,"[Pizza, Cultural-On, Stuff, BioTop, Pizza, Bio...","[Soho SubclassOf(VegetarianPizzaEquivalent1), ...","[What is a soho?, What is a monumental area or..."
3,[X] EquivalentTo([A]),Gras EquivalentTo(Grass),What is [X]?,What is a gras?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,56,231159514,"[Stuff, BioTop, Cultural-On, Pizza, Pizza, Piz...","[MicellarColloid SubclassOf(MixedStuff), Canon...","[What is a micellar colloid?, What is canonici..."
4,[X] SubclassOf([Y]),Warthog SubclassOf(Animal),What is [X]?,What is a warthog?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,23,3904498325,"[BioTop, Stuff, Cultural-On, Pizza, Stuff, Stu...",[NoncanonicalValueRegion SubclassOf(ValueRegio...,"[What is a noncanonical value region?, What is..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,[X] SubclassOf([prop] some [Y]),hasWordConjunct SubclassOf(hasChild some Token),True or false: [X] [prop/*OP_HAS_NOUNS-third] ...,True or false: A has word conjunct has a child...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427443,1569547285,"[Pizza, AWO, Cultural-On, Stuff, AWO, AWO, AWO...",[MozzarellaTopping SubclassOf(hasSpiciness som...,[True or false: A mozzarella topping has a spi...
426,[X] SubclassOf([prop] some [Y]),hasConjunct SubclassOf(hasParent some Coordina...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does a has conjunct have a parent that is some...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427438,1921824982,"[Cultural-On, Pizza, Stuff, AWO, Pizza, AWO, S...",[CulturalInstituteOrSite SubclassOf(hasSite so...,[Does a cultural institute or site have a site...
427,[X] SubclassOf([prop] some [Y]),NonspecificPronoun SubclassOf(hasSpecificity s...,[X] [prop/*OP_HAS_NOUNS-third] that is some [Y...,A nonspecific pronoun has a specificity that i...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427436,2951387684,"[Stuff, Pizza, Cultural-On, AWO, AWO, Pizza, S...",[Piece SubclassOf(properPartOf some AmountOfSt...,[Is a piece proper part of some amount of stuf...
428,[X] SubclassOf([prop] some [Y]),hasWordConjunct SubclassOf(hasChild some Token),[X] [prop/*OP_HAS_NOUNS-third] that is some [Y...,A has word conjunct has a child that is some t...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427442,2979572471,"[Stuff, AWO, Cultural-On, Pizza, Cultural-On, ...",[Solution SubclassOf(hasPart some PhysicalEndu...,[A solution has part that is some physical end...
429,[X] SubclassOf([prop] some [Y]),NonspecificPronoun SubclassOf(hasSpecificity s...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does a nonspecific pronoun have a specificity ...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427435,3158202469,"[Cultural-On, Stuff, AWO, Pizza, AWO, Cultural...",[HolderOfArchive SubclassOf(hasCISType some CI...,[A holder of archives has a type that is some ...

Reload the dataset as parquet

In [10]:
import pyarrow.parquet as pq
df = pq.read_table("../dataset/qgenllm-ds-seed-123-few-shots.parquet").to_pandas()

display(df)

,axiom_pattern,axiom,template,question,question_type,op_category,ontology,file,question_type_short,op_category_short,question_id,seed,q_from_os,sample_axioms,sample_questions
0,[X] SubclassOf([Y]),Grass SubclassOf(Plant),What is [X]?,What is grass?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,8,66316748,"[BioTop, Pizza, Stuff, Cultural-On, Cultural-O...","[Universe SubclassOf(Condition), ThinAndCrispy...","[What is universe?, What is a thin and crispy ..."
1,[X] SubclassOf([Y]),Impala SubclassOf(TerrestrialAnimal),What is [X]?,What is an impala?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,37,2930678936,"[Cultural-On, Stuff, BioTop, Pizza, Pizza, Cul...",[CulturalInstituteOrSite SubclassOf(CulturalEn...,"[What is a cultural institute or site?, What i..."
2,[X] SubclassOf([Y]),Camelopard SubclassOf(Animal),What is [X]?,What is a camelopard?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,40,2546691362,"[Pizza, Cultural-On, Stuff, BioTop, Pizza, Bio...","[Soho SubclassOf(VegetarianPizzaEquivalent1), ...","[What is a soho?, What is a monumental area or..."
3,[X] EquivalentTo([A]),Gras EquivalentTo(Grass),What is [X]?,What is a gras?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,56,231159514,"[Stuff, BioTop, Cultural-On, Pizza, Pizza, Piz...","[MicellarColloid SubclassOf(MixedStuff), Canon...","[What is a micellar colloid?, What is canonici..."
4,[X] SubclassOf([Y]),Warthog SubclassOf(Animal),What is [X]?,What is a warthog?,Definition,OP_DEFINITION,AWO,Definition.csv,def,definition,23,3904498325,"[BioTop, Stuff, Cultural-On, Pizza, Stuff, Stu...",[NoncanonicalValueRegion SubclassOf(ValueRegio...,"[What is a noncanonical value region?, What is..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,[X] SubclassOf([prop] some [Y]),hasWordConjunct SubclassOf(hasChild some Token),True or false: [X] [prop/*OP_HAS_NOUNS-third] ...,True or false: A has word conjunct has a child...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427443,1569547285,"[Pizza, AWO, Cultural-On, Stuff, AWO, AWO, AWO...",[MozzarellaTopping SubclassOf(hasSpiciness som...,[True or false: A mozzarella topping has a spi...
426,[X] SubclassOf([prop] some [Y]),hasConjunct SubclassOf(hasParent some Coordina...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does a has conjunct have a parent that is some...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427438,1921824982,"[Cultural-On, Pizza, Stuff, AWO, Pizza, AWO, S...",[CulturalInstituteOrSite SubclassOf(hasSite so...,[Does a cultural institute or site have a site...
427,[X] SubclassOf([prop] some [Y]),NonspecificPronoun SubclassOf(hasSpecificity s...,[X] [prop/*OP_HAS_NOUNS-third] that is some [Y...,A nonspecific pronoun has a specificity that i...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427436,2951387684,"[Stuff, Pizza, Cultural-On, AWO, AWO, Pizza, S...",[Piece SubclassOf(properPartOf some AmountOfSt...,[Is a piece proper part of some amount of stuf...
428,[X] SubclassOf([prop] some [Y]),hasWordConjunct SubclassOf(hasChild some Token),[X] [prop/*OP_HAS_NOUNS-third] that is some [Y...,A has word conjunct has a child that is some t...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427442,2979572471,"[Stuff, AWO, Cultural-On, Pizza, Cultural-On, ...",[Solution SubclassOf(hasPart some PhysicalEndu...,[A solution has part that is some physical end...
429,[X] SubclassOf([prop] some [Y]),NonspecificPronoun SubclassOf(hasSpecificity s...,Does [X] [prop/*OP_HAS_NOUNS-infinitive] that ...,Does a nonspecific pronoun have a specificity ...,op_Yes-No-2-part-1-rel+1-quant-some,OP_HAS_NOUNS,olia,Yes-No-2-part-1-rel+1-quant-some.csv,yn2p1r_1_qs,has_nouns,427435,3158202469,"[Cultural-On, Stuff, AWO, Pizza, AWO, Cultural...",[HolderOfArchive SubclassOf(hasCISType some CI...,[A holder of archives has a type that is some ...